name: Docker
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build --tag operator:latest .
      - name: Release
        run: |
          DOCKER_TAG="quay.io/rtctunnel/operator:$(basename "$GITHUB_REF")"

          echo "releasing username=$DOCKER_USERNAME tag=$DOCKER_TAG"

          echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin quay.io
          docker tag operator:latest "$DOCKER_TAG"
          docker push "$DOCKER_TAG"
        env:
          DOCKER_USERNAME: rtctunnel+github
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_REF: ${{ github.ref }}
